---
title: "AR cover"
author: "Ewout Knoester"
date: "17/08/2022"
output: html_document
---

```{r setup, include=FALSE}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks
options(scipen = 50) # Have all numbers in non-scientific notation

library(car) # Anovas
library(cowplot) # Plot grid
library(data.table)
library(emmeans) # Pairwise comparisons
library(flextable) # Layout word table
library(ggthemes) # pretty plots
library(NCmisc) # Check packages used
library(nlme) # GLS
library(betareg) # Beta regression
library(officer) # Move table into word
library(panelr) # Convert data from wide to long
library(plyr) # Join (vlookup)
library(readxl) # Import excel sheets
library(tidyverse) # Data manipulation and plotting
library(writexl) # Export Excel

data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(sum = sum(x[[col]]),
      mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]])))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- plyr::rename(data_sum, c("mean" = varname))
 return(data_sum)
}

```

# Data selection (preparing dataset for archiving & sharing)
```{r data selection, warning= FALSE}

# RAW data
df0.raw <- read.csv("Raw data/Coralnet_Annotations_Structural complexity_2022-08.csv")

# Select relevant columns
df1.clean <- select(df0.raw, c("Name","Date", "Site", "Patch", "Treatment", "Structure", "Label"))
colnames(df1.clean)[which(names(df1.clean) == "Name")] <- "Pic"

# Get full names and functional groups from labelset
labelset <- read.csv("Raw data/Coralnet_Labelset.csv")
colnames(labelset)[which(names(labelset) == "Label")] <- "Name"
colnames(labelset)[which(names(labelset) == "Code")] <- "Label"

# Merge to combine info
df1.clean <- left_join(df1.clean, labelset, by = "Label")

# Cleanup
colnames(df1.clean)[which(names(df1.clean) == "Structure")] <- "Number"
colnames(df1.clean)[which(names(df1.clean) == "Treatment")] <- "Structure"

df1.clean$Treatment <- ifelse(grepl("BRU", df1.clean$Patch), "BRU", 
                       ifelse(grepl("CAKE", df1.clean$Patch), "Cake",
                       ifelse(grepl("CAGE", df1.clean$Patch), "Cage",       
                       ifelse(grepl("COMP", df1.clean$Patch), "Compound",
                       ifelse(grepl("Quadrat", df1.clean$Structure) & grepl("\\(", df1.clean$Patch), "Ref (+)",
                       ifelse(grepl("DISK", df1.clean$Structure) & grepl("\\(", df1.clean$Patch), "Ref (+)",
                       ifelse(grepl("Quadrat", df1.clean$Structure), "Ref (-)",
                       ifelse(grepl("DISK", df1.clean$Structure), "Ref (-)", "Other"))))))))

# EXPORT DATA SELECTION
write_xlsx(df1.clean, "Structural complexity_AR cover_2022-08.xlsx")

```

# Data prep 
<!--
Data info:
  Data of several types of benthic surveys
  Dead corals were classified as Dead when the genus could still be recognized or as Bare rock when not
-->
```{r data prep}

# Load data
df2.selex <- read_excel("Structural complexity_AR cover_2022-08.xlsx")

## Set groups
#df2.selex$Super.group[df2.selex$Super.group == "Bare substrate"] <- "Soft substrate"

# Set order of substrates
df2.selex$Functional.group <- factor(df2.selex$Functional.group,  levels=c("Not applicable","Soft substrate", "Hard substrate", "EAM", "Other",  "Sponge", "Tunicate", "Hydroid", "Macroalgae", "Soft coral", "Hard coral"))

# SUBSETS
# --- AR COVER ---
df3.ARC <- select(df2.selex, c('Pic', 'Site', 'Treatment', 'Patch', 'Structure', 'Number', 'Functional.group'))

# Select surveys
## Leave out points outside frame
df3.ARC <- subset(df3.ARC, Functional.group != "Not applicable")
df3.ARC$Functional.group <- factor(df3.ARC$Functional.group)

# Get total counts per survey (not always 50 because of Not applicable points removed)
df3.ARC.counts <- df3.ARC %>%
          group_by(Pic) %>%
          tally()

# Get counts per Functional group
df3.ARC <- df3.ARC %>%
          group_by(Pic, Site, Treatment, Patch, Structure, Number, Functional.group, .drop = FALSE) %>%
          tally()

# Get cover by dividing Functional group counts/ total counts
df3.ARC <- left_join(df3.ARC, df3.ARC.counts, by = "Pic") # Combine data frames
df3.ARC$Cover <- df3.ARC$n.x / df3.ARC$n.y * 100 

df3.ARC.Structure <- data_summary(df3.ARC, varname = "Cover", groupnames = c("Treatment", "Patch", "Structure", "Number", "Functional.group"))
df3.ARC.Structure <- select (df3.ARC.Structure, -c("sum", "sd", "n", "se"))
write_xlsx(df3.ARC.Structure, "Correlation data/Structural complexity_Correlations_AR cover.xlsx")

# Deselect disks (ie focus from here onwards on ARs only)
df3.ARC.ND <- df3.ARC[df3.ARC$Structure != "DISK", ]

# First summarize per patch (average over all AR structures)
df3.ARC.Patch <- data_summary(df3.ARC.ND, varname = "Cover", groupnames = c("Treatment", "Patch", "Functional.group"))

# Then summarize per Treatment (average over all patches)
df3.ARC.Treatment <- data_summary(df3.ARC.Patch, varname = "Cover", groupnames = c("Treatment", "Functional.group"))
df3.ARC.Treatment <- select (df3.ARC.Treatment, -c("sum", "sd"))

```

# Plots
```{r plots}

# AR cover by Treatment
ggplot(df3.ARC.Treatment, aes(fill=Functional.group, y=Cover, x=Treatment)) + 
    geom_bar(position="fill", stat="identity")+
    #scale_fill_manual(values = c("#EAEDED", "#909497", "#424949", "#229954", "#F9E79F", "#E67E22"))+
    labs(y = "Benthic cover (%)", x = "Treatment", fill = "Substrate")+
    scale_y_continuous(expand = c(0,0))+
    theme_economist()+
    theme(
      axis.title.x = element_text(color="black", vjust=-2, size = 14),
      axis.text.x=element_text(size=12, face = "bold.italic", vjust=0.5, angle = -35, hjust=0),
      axis.title.y = element_text(color="black" , vjust=4, size = 14),
      axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
      plot.margin = unit(c(0.5,3.5,0.5,0.5), "cm"),
      panel.background = element_rect(fill = "#FCFCFC"),
      plot.background = element_rect(fill = "#FFFFFF"),
      panel.grid.major = element_line(colour = "#797979", size = 0.3),
      axis.ticks.length = unit(0.15, "cm")
      )
# Similar to the benthic survey plot, so no need to use or save

```


