---
title: "Fish"
author: "Ewout Knoester"
date: "23/08/2022"
output: html_document
---

# Setup
```{r setup}
rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks
options(scipen = 99) # Have all numbers in non-scientific notation

library(readxl) # Join data frames (vlookup)
library(cowplot) # Combine plots
library(data.table)
library(ggthemes) # pretty plots
library(flextable) # Layout word table
library(tidyverse) # Beta regression
library(vegan) # Export Excel
library(gridExtra)
library(emmeans) # Select text from string
library(lmerTest) # GLS
library(officer) # Move table into word
library(gridGraphics) # Combine base and ggplots
library(car) # glm model validation
library(viridis) # Convert data from wide to long
library(pairwiseAdonis)
library(writexl) # Export Excel

# Function to facilitate averaging data frame
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      sd = sd(x[[col]], na.rm=TRUE),
      sum  = sum(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x[[col]])))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- plyr::rename(data_sum, c("mean" = varname))
 return(data_sum)
}

# Set colours for Treatments
co <- c("#B0E54D", "#6FDCD9", "#F0C862", "#EC86BF","#D04E08", "#0673B0") # Colour palette

```

# Data selection (preparing dataset for archiving & sharing)
```{r data selection, warning= FALSE}

# ---- RAW DATA ----
## Load
### 2021
divRAW.2021 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2021-2022_2022-08.xlsm", sheet = 3, skip = 6))
div.2021 <- divRAW.2021[!is.na(divRAW.2021$Species),] # Remove unrelevant row
div.2021 <- select(div.2021, -c(1, 3:11)) # Remove unrelevant columns
div.2021$Species <- sub("\\.", "", div.2021$Species) # Remove points from species names

### 2020
divRAW.2020 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2020_2022-08.xlsm", sheet = 3, skip = 6))
div.2020 <- divRAW.2020[!is.na(divRAW.2020$Species),] # Remove unrelevant row
div.2020 <- select(div.2020, -c(1, 3:11)) # Remove unrelevant columns
div.2020$Species <- sub("\\.", "", div.2020$Species) # Remove points from species names

### 2019
divRAW.2019 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2019_2022-08.xlsm", sheet = 3, skip = 6))
div.2019 <- divRAW.2019[!is.na(divRAW.2019$Species),] # Remove unrelevant row
div.2019 <- select(div.2019, -c(1, 3:11)) # Remove unrelevant columns
div.2019$Species <- sub("\\.", "", div.2019$Species) # Remove points from species names

### 2018
divRAW.2018 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2017-2018_2022-08.xlsm", sheet = 3, skip = 6))
div.2018 <- divRAW.2018[!is.na(divRAW.2018$Species),] # Remove unrelevant row
div.2018 <- select(div.2018, -c(1, 3:11)) # Remove unrelevant columns
div.2018$Species <- sub("\\.", "", div.2018$Species) # Remove points from species names

## Merge all years
div <- left_join(div.2021, div.2020, by = "Species")
div <- left_join(div, div.2019, by = "Species")
div <- left_join(div, div.2018, by = "Species")

## Get rid of the columns not needed (pre-calculated biomasses)
div <- div[, -grep(pattern= 'g_', colnames(div))]
div <- div[, -grep(pattern='kgha', colnames(div))]
div <- div[, -grep(pattern='TOT', colnames(div))]
div$Species <- as.factor(div$Species)

## Remove Atherinomorus (silversides), because enormous swarms
div <- div[!(div$Species=='Atherinomorus sp'),]

# Net NAs to 0 
div[is.na(div)] <- 0

## Set column names (order of surveys won't match original Excel numbering anymore: start numbering at newer survey years)
surveys.tot <- (ncol(div) - 1)/13
colname <- c("Species", paste0(rep(c("1_", "2_", "3_", "4_", "5_", "6_", "7_", "8_", "9_", "10_", "11_", "12_", "Coloured_"), surveys.tot), rep(1:surveys.tot, each = 13)))
colnames(div) <- colname

## Go to long format
div <- setDT(div)
div <- melt(div, 
            id.vars = 'Species', variable.name = 'SurveyNo', 
            measure.vars = patterns('^1_', '^2_', '^3_', '^4_', '^5_', '^6_',
                                    '^7_', '^8_', '^9_', '^10_', '^11_', '^12_', '^Coloured_'),
            value.name = c('1.25', '3.75', '6.25', '8.75', '12.5', '17.5',
                           '25', '35', '45', '75', '125', '175', 'Coloured'))
div$Coloured[div$Coloured == 0] <- 12 # Set non-coloured value (12) for missing data

# ---- META DATA ----
## ==== Meta data Surveys ====
### 2021
SurveysData.2021 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2021-2022_2022-08.xlsm", sheet = "Data")) 
SurveysData.2021 <- SurveysData.2021[!is.na(SurveysData.2021$Date),] # Remove empty rows

### 2020
SurveysData.2020 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2020_2022-08.xlsm", sheet = "Data")) 

### 2019
SurveysData.2019 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2019_2022-08.xlsm", sheet = "Data")) 

### 2018
SurveysData.2018 <- as.data.frame(read_excel("Raw data/Fish surveys_DATABASE_2017-2018_2022-08.xlsm", sheet = "Data")) 

### Merge years
SurveysData <- rbind(SurveysData.2021, SurveysData.2020, SurveysData.2019, SurveysData.2018)

### Clean up
SurveysData$SurveyNo <- as.factor(seq(1, surveys.tot, by = 1))
SurveysData <- SurveysData[,-c(6:8,27:50)] # Remove unnecessary columns 

## ==== Meta data Patches ====
###Treatment and Zone info
reeftype <- as.data.frame(read_excel("Raw data/SpeciesList_2022-08.xlsx", sheet = "ReefType"))

### More meta data
metadata <- as.data.frame(read_excel("Raw data/Metadata ARs_2022-08.xlsx", sheet= "Metadata"))
metadata <- metadata[c(2:5,11)] # Select relevant columns

## ==== Metadatas combined ====
metadata <- merge(reeftype, metadata, by = "Transect") # Only retains the 60 patches
SurveysDataPlus <- merge(SurveysData, metadata, all.x = TRUE)

## Cleanup
SurveysDataPlus <- SurveysDataPlus[order(SurveysDataPlus$SurveyNo),]

## Set study years
SurveysDataPlus$Study <- lubridate::year(SurveysDataPlus$Date)
SurveysDataPlus$Study[SurveysDataPlus$Study == 2022] <- 2021 # For convenience

# For permutation test
SurveysDataPlus$Interaction <- as.factor(paste(as.character(SurveysDataPlus$ReefType), as.character(SurveysDataPlus$Study))) 

# Set hard substrate
SurveysDataPlus$Hard.substrate_cor <- SurveysDataPlus$Hard.coral + SurveysDataPlus$Rock #one of the external factors
SurveysDataPlus$Hard.substrate_cor[SurveysDataPlus$ReefType=='Positive'] <- NA #Hard substrate on reefs not considered noise
Hard_substrate_cor <- aggregate(Hard.substrate_cor ~ Transect, SurveysDataPlus[SurveysDataPlus$Study=='2021',], mean)
metadata <- merge(metadata,Hard_substrate_cor, all.x=T)

# ==== Species information ====
specieslist <- as.data.frame(read_excel("Raw data/SpeciesList_2022-08.xlsx", sheet = "SpeciesList"))
specieslist$Species <- sub("\\.", "", specieslist$Species) # Remove points from species names

# ==== Select surveys ====
## Categorize type of surveys
SurveysDataPlus$Transect[SurveysDataPlus$Transect == "NA"] <- "No"
SurveysDataPlus$ReefType  <- ifelse(grepl("BRU", SurveysDataPlus$Transect), "BRU", 
              ifelse(grepl("CAKE", SurveysDataPlus$Transect), "Cake",
              ifelse(grepl("CAGE", SurveysDataPlus$Transect), "Cage",       
              ifelse(grepl("COMP", SurveysDataPlus$Transect), "Comp",
              ifelse(grepl("\\(F-R", SurveysDataPlus$Transect), "Ref (+)", 
                ifelse(grepl("\\(F-C-1", SurveysDataPlus$Transect), "Ref (+) extra", # No ARs placed yet
                ifelse(grepl("F-C-1", SurveysDataPlus$Transect), "Ref (-) extra", # No ARs placed yet
                ifelse(grepl("\\(F-C-2", SurveysDataPlus$Transect), "Ref (+) extra", # No ARs placed yet
                ifelse(grepl("F-C-2", SurveysDataPlus$Transect), "Ref (-) extra", # No ARs placed yet
              ifelse(grepl("\\(NT-R", SurveysDataPlus$Transect), "Ref (+)",
                ifelse(grepl("\\(NT-C-3", SurveysDataPlus$Transect), "Ref (+) extra", # No ARs placed yet
                ifelse(grepl("NT-C-3", SurveysDataPlus$Transect), "Ref (-) extra", # No ARs placed yet
                ifelse(grepl("\\(NT-C-4", SurveysDataPlus$Transect), "Ref (+) extra", # No ARs placed yet
                ifelse(grepl("NT-C-4", SurveysDataPlus$Transect), "Ref (-) extra", # No ARs placed yet
                ifelse(grepl("\\(NT-C-5", SurveysDataPlus$Transect), "Ref (+) extra", # No ARs placed yet?
                ifelse(grepl("NT-C-5", SurveysDataPlus$Transect), "Ref (-) extra", # No ARs placed yet? 
              ifelse(grepl("F-R", SurveysDataPlus$Transect), "Ref (-)",
              ifelse(grepl("NT-R", SurveysDataPlus$Transect), "Ref (-)",
              ifelse(grepl("\\(", SurveysDataPlus$Transect), "Ref (+) extra plus", 
              ifelse(grepl("CMA-", SurveysDataPlus$Transect), "Ref (-) extra plus", 
              ifelse(grepl("NT-C", SurveysDataPlus$Transect) & SurveysDataPlus$Study == 2018, "Ref (-) before",
              ifelse(grepl("NT-S", SurveysDataPlus$Transect) & SurveysDataPlus$Study == 2018, "Ref (-) before",
              ifelse(grepl("F-S", SurveysDataPlus$Transect) & SurveysDataPlus$Study == 2018, "Ref (-) before",
              ifelse(grepl("F-C", SurveysDataPlus$Transect) & SurveysDataPlus$Study == 2018, "Ref (-) before",
              "Other"))))))))))))))))))))))))

## Select
SurveysDataPlus <- SurveysDataPlus[SurveysDataPlus$ReefType != "Other", ] # Only Include the data from the experiment
SurveysDataPlus <- subset(SurveysDataPlus, !grepl("wrong", SurveysDataPlus$Comments)) # Survey done on the wrong location

# Select only surveys of div data data are present in SurveysDataPlus
div <- div[div$SurveyNo %in% c(unlist(na.omit(SurveysDataPlus$SurveyNo))),]

SurveysDataPlus <- select(SurveysDataPlus, c(24, 1, 3, 5, 25, 31, 17, 21:23))

specieslist <- select(specieslist, c("Species", "Diet", "a", "b"))

metadata <- select(metadata, -c("ReefType", "Zone"))

# ==== Export data sets ====
## Fish survey data
write_xlsx(div, "Structural complexity_Fish surveys_2022-08.xlsx")

## Fish survey metadata
write_xlsx(SurveysDataPlus, "Structural complexity_Fish metadata_2022-08.xlsx")

## Fish species list
write_xlsx(specieslist, "Structural complexity_Fish species list_2022-08.xlsx")

## AR pach metadata
write_xlsx(metadata, "Structural complexity_AR patch metadata_2022-08.xlsx")

```

# Load data
```{r}

# Load data sets
fish <- as.data.frame(read_excel("Structural complexity_Fish surveys_2022-08.xlsx"))
surveys <- as.data.frame(read_excel("Structural complexity_Fish metadata_2022-08.xlsx"))
specieslist <- as.data.frame(read_excel("Structural complexity_Fish species list_2022-08.xlsx"))
metadata <- as.data.frame(read_excel("Structural complexity_AR patch metadata_2022-08.xlsx"))

# Set data types
fish$SurveyNo <- as.numeric(fish$SurveyNo)
surveys$SurveyNo <- as.numeric(surveys$SurveyNo)

tofactors <- c('Transect', 'Observer', 'ReefType', 'Study') 
surveys[tofactors] <- lapply(surveys[tofactors], factor)

tofactors <- c('Species', 'Diet')
specieslist[tofactors] <- lapply(specieslist[tofactors], factor)

tofactors <- c('Transect')
metadata[tofactors] <- lapply(metadata[tofactors], factor)

# Get total list of surveys (also those without any observations)
totsur <- as.data.frame(unique(fish$SurveyNo)) 
names(totsur) <- "SurveyNo"

```

# Richness
```{r richness}

# ---- DATA PREP ----
# RICHNESS
## Remove colour codings (for non-instataneous data) from Diversity data frame
div <- select(fish, -c('Coloured'))
div$SpeciesAbundance <- rowSums(div[, 3:14]) # Sum abundance over all size categories
div <- div[div$SpeciesAbundance != 0,] # Remove the rows with no abundance
#divx <- div[!grepl(".*sp$", div$Species),]

## Make already a grouping, for Diversity analysis on Diet level
divDiet <- spread(merge(div, specieslist, all.x=T), key = Diet, value = SpeciesAbundance) # Diet from long to wide
divDiet <- divDiet[,-c(1,3:16)] # Remove unnecessary columns
divDiet <- merge(divDiet, totsur, all.y=T) # Re-add surveys without observations
divDiet[is.na(divDiet)] <- 0
divDiet <- aggregate(. ~ SurveyNo, data = divDiet, FUN = sum) # Sum each Diet per Survey

## Get fish surveys from long to wide
div <- spread(div, key = Species, value = SpeciesAbundance) # Fish surveys data from long to wide
div <- div[,-c(2:13)] #Remove unnecessary columns
div[is.na(div)] <- 0 
div <- aggregate(. ~ SurveyNo, data=div, FUN=sum) #Here we combine all species for each survey
div <- merge(div, totsur, all.y=T) # Re-add surveys without observations
div[is.na(div)] <- 0 

## Total species encountered per Treatment
metamini <- select(surveys, c("SurveyNo", "ReefType", "Study"))
divtot <- left_join(div, metamini, by = "SurveyNo")
divtot <- subset(divtot, Study == 2021)
divtot <- select(divtot, -c("Study", "SurveyNo"))
divtot <- aggregate(. ~ ReefType, divtot, sum)
divtot$ReefType <- as.character(divtot$ReefType)
divtot <- as.data.frame(cbind(divtot$ReefType, as.numeric(rowSums(divtot!=0) - 1)))

## Calculate Richness
divsum <- as.data.frame(cbind(div$SurveyNo, as.numeric(rowSums(div!=0) - 1)))
names(divsum) <- c("SurveyNo", "S")
divsum <- merge(surveys, divsum, all.x=T) # Merge with selected survey metadata
divsum <- select(divsum, -c("Visibility", "Radius", "Area", "Comments"))

## Average surveys done simultaneously
divsumsubmeans <- subset(divsum, Observer != "Cindy" & Observer != "Mercy") # Deselect practice surveys 
divsumsubmeans <- aggregate(S ~ Transect + Date + Study + ReefType, divsumsubmeans, mean)
divsumsubmeans <- merge(divsumsubmeans, metadata, all.x=T, by = "Transect") # Add Patch metadata

## Average over replicate transects within each Study year
divsumsubtransmeans <- subset(divsum, Observer != "Cindy" & Observer != "Mercy") # Deselect practice surveys 
divsumsubtransmeans <- aggregate(S ~ Transect + Study + ReefType, divsumsubtransmeans, mean)
divsumsubtransmeans <- merge(divsumsubtransmeans, metadata, all.x=T) # Add Patch metadata

# SPECIES LISTS
## Create data frame
Specs <- left_join(surveys, div, by = "SurveyNo")

## Select relevant data
Specs <- subset(Specs, Observer != "Cindy" & Observer != "Mercy" & Study != 2018)
Specs <- subset(Specs, ReefType == "Ref (-)" | ReefType == "Ref (+)")

## Cleanup
Specs <- select(Specs, -c("SurveyNo", "Observer", "Date", "Visibility", "Radius", "Area", "Comments"))

## Sum over Study + ReefType + Observer
Specs.sum <- aggregate(. ~ Study + ReefType + Transect, Specs, sum)
Specs.sum <- select(Specs.sum, -c("Transect"))

# ---- MODELLING ----

## ==== 2021 - depth adjusted ====
## Initial explorations showed that Depth influenced Richness, other co-variates (distance to reef, coral cover etc) did not
divsumsubmeans.2021 <- subset(divsumsubmeans, Study == 2021)
divsumsubtransmeans.2021 <- subset(divsumsubtransmeans, Study == 2021)

### Including Depth lowers AIC for Interaction model (both Study years)
AIC(lmer(S ~ Depth_Abs + ReefType + (1|Transect), data = divsumsubmeans.2021),
    lmer(S ~ ReefType + (1|Transect), data = divsumsubmeans.2021))

### Best model is therefore one that includes depth
lmerSmeancor.2021 <- lmer(S ~ Depth_Abs + ReefType + (1|Transect), data = divsumsubmeans.2021)

### Main effects for Study and reeftype are significant, interaction is not
car::Anova(lmerSmeancor.2021)
summary(lmerSmeancor.2021)

### Model validation
mod <- lmerSmeancor.2021 # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(divsumsubmeans.2021$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ divsumsubmeans.2021$S) # response data vs fitted
par(op)

### Post hoc
emmScor.2021 <- emmeans(lmerSmeancor.2021, specs = pairwise ~ ReefType, adjust = 'tukey', type = "response") 
emmScorsum.2021 <- multcomp::cld(emmScor.2021$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE) # get CLD
emmScorsum.2021 <- emmScorsum.2021 %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

## ==== 2020 - depth adjusted ====
## Initial explorations showed that Depth influenced Richness, other co-variates (distance to reef, coral cover etc) did not
divsumsubmeans.2020 <- subset(divsumsubmeans, Study == 2020 & !grepl("extra", divsumsubmeans$ReefType))
divsumsubtransmeans.2020 <- subset(divsumsubtransmeans, Study == 2020 & !grepl("extra", divsumsubtransmeans$ReefType))

### Including Depth lowers AIC for Interaction model (both Study years)
AIC(lmer(S ~ Depth_Abs + ReefType + (1|Transect), data = divsumsubmeans.2020),
    lmer(S ~ ReefType + (1|Transect), data = divsumsubmeans.2020))

### Best model is therefore one that includes depth
lmerSmeancor.2020 <- lmer(S ~ Depth_Abs + ReefType + (1|Transect), data = divsumsubmeans.2020)

### Main effects for Study and reeftype are significant, interaction is not
Anova(lmerSmeancor.2020)
summary(lmerSmeancor.2020)

### Model validation
mod <- lmerSmeancor.2020 # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(divsumsubmeans.2020$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ divsumsubmeans.2020$S) # response data vs fitted
par(op)

### Post hoc
emmScor.2020 <- emmeans(lmerSmeancor.2020, specs = pairwise ~ ReefType, adjust = 'tukey', type = "response") 
emmScorsum.2020 <- multcomp::cld(emmScor.2020$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE) # get CLD
emmScorsum.2020 <- emmScorsum.2020 %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

## ==== Throughout the years ====
divsumsubmeans.years <- subset(divsumsubmeans, (ReefType == "Ref (-)" | ReefType == "Ref (+)") & (Study != 2018))
divsumsubtransmeans.years<- subset(divsumsubtransmeans, (ReefType == "Ref (-)" | ReefType == "Ref (+)") & (Study != 2018))

### Model
lmerSmeancor.years<- lmer(S ~ ReefType*Study + (1|Transect), data = divsumsubmeans.years)
Anova(lmerSmeancor.years)
summary(lmerSmeancor.years)

### Model validation
mod <- lmerSmeancor.years # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(divsumsubmeans.years$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(divsumsubmeans.years$Study, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ divsumsubmeans.years$S) # response data vs fitted
par(op)

### Post hoc
emmScor.years <- emmeans(lmerSmeancor.years, specs = pairwise ~ Study|ReefType,
                         adjust = 'tukey', type = "response") 
emmScorsum.years <- multcomp::cld(emmScor.years$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE)
emmScorsum.years <- emmScorsum.years %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# ---- PLOTS ----
## ==== 2021 - depth adjusted ====
### Adjust raw data points for depth, based on EMMEANS
lmerSmeancor.2021.coef <- as.data.frame(summary(lmerSmeancor.2021)$coefficients)
lmerSmeancor.2021.coef <- tibble::rownames_to_column(lmerSmeancor.2021.coef, "Name")
lmerSmeancor.2021.coef.b_Depth <- lmerSmeancor.2021.coef[lmerSmeancor.2021.coef$Name == "Depth_Abs", "Estimate"]
lmerSmeancor.2021.coef.mean_Depth <- mean(as.data.frame(ref_grid(lmerSmeancor.2021))$Depth_Abs)
divsumsubmeans.2021$S.adj <- divsumsubmeans.2021$S + lmerSmeancor.2021.coef.b_Depth * (lmerSmeancor.2021.coef.mean_Depth - divsumsubmeans.2021$Depth_Abs)
  
### Get average per Patch
divsumsubmeans.2021.adj <- aggregate(S.adj ~ Transect + Study + ReefType, divsumsubmeans.2021, mean)

### Richness plot 2021 - depth adjusted
Divplot <- ggplot(data = divsumsubmeans.2021.adj, aes(x = ReefType, colour = ReefType, y = S.adj))+
    geom_jitter(width = 0.2, size = 2)+
    scale_colour_manual(values = co)+
    geom_point(data = emmScorsum.2021, aes(y = emmean), size = 4, colour='black')+
    geom_errorbar(data = emmScorsum.2021, width = 0.1, colour='black', size=0.8,
                  aes(y = emmean, ymin = emmean - SE, ymax = emmean + SE))+
    geom_text(data=emmScorsum.2021, 
              aes(label = .group, y = emmean + 2.2*SE), colour = 'black', size = 7)+
    labs(y = "Fish species richness (S)", x = "Treatment")+
    scale_y_continuous(breaks = c(10, 20, 30))+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 3),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          legend.position="none")

## ==== 2020 - depth adjusted ====
### Adjust raw data points for depth, based on EMMEANS
lmerSmeancor.2020.coef <- as.data.frame(summary(lmerSmeancor.2020)$coefficients)
lmerSmeancor.2020.coef <- tibble::rownames_to_column(lmerSmeancor.2020.coef, "Name")
lmerSmeancor.2020.coef.b_Depth <- lmerSmeancor.2020.coef[lmerSmeancor.2020.coef$Name == "Depth_Abs", "Estimate"]
lmerSmeancor.2020.coef.mean_Depth <- mean(as.data.frame(ref_grid(lmerSmeancor.2020))$Depth_Abs)
divsumsubmeans.2020$S.adj <- divsumsubmeans.2020$S + lmerSmeancor.2020.coef.b_Depth * (lmerSmeancor.2020.coef.mean_Depth - divsumsubmeans.2020$Depth_Abs)
  
### Get average per Patch
divsumsubmeans.2020.adj <- aggregate(S.adj ~ Transect + Study + ReefType, divsumsubmeans.2020, mean)

### Richness plot 2020 - depth adjusted
ggplot(data = divsumsubmeans.2020.adj, aes(x = ReefType, colour = ReefType, y = S.adj))+
    geom_jitter(width = 0.2, size = 2)+
    scale_colour_manual(values = co)+
    geom_point(data = emmScorsum.2020, aes(y = emmean), size = 4, colour='black')+
    geom_errorbar(data = emmScorsum.2020, width = 0.1, colour='black', size=0.8,
                  aes(y = emmean, ymin = emmean - SE, ymax = emmean + SE))+
    geom_text(data=emmScorsum.2020, 
              aes(label = .group, y = emmean + 2*SE), colour = 'black', size = 7)+
    labs(y = "Fish species richness (S)", x = "Treatment")+
    scale_y_continuous(breaks = c(10, 20, 30))+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 3),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_text(size = 14, face = "plain", vjust = -0.5),
          axis.text.x = element_text(size = 14, face = "bold", vjust = 0.5),
          legend.position="none")
#ggsave("Fish_Richness_2020 - depth adjusted.tiff", width = 23, height = 14, units = "cm", dpi=1200, compression = "lzw")

## ==== Throughout the Years ====

divsumsubtransmeans.years$ReefType <- ifelse(divsumsubtransmeans.years$ReefType == "Ref (-)", "Control", 
                                      ifelse(divsumsubtransmeans.years$ReefType == "Ref (+)", "Reference", "Other"))
emmScorsum.years$ReefType <- ifelse(emmScorsum.years$ReefType == "Ref (-)", "Control", 
                                      ifelse(emmScorsum.years$ReefType == "Ref (+)", "Reference", "Other"))

### Richness throughout the years plot
s.years <- ggplot(data = divsumsubtransmeans.years, aes(x = Study, colour = ReefType, y = S))+
    facet_grid(.~ReefType)+
    geom_jitter(width = 0.2, size = 2)+
    geom_point(data = emmScorsum.years, aes(y = emmean), size = 4, colour='black')+
    geom_errorbar(data = emmScorsum.years, width = 0.1, colour='black', size=0.8,
                  aes(y = emmean, ymin = emmean - SE, ymax = emmean + SE))+
    geom_text(data=emmScorsum.years, 
              aes(label = .group, y = emmean + 3*SE), colour = 'black', size = 7)+
    labs(y = "Fish species richness (S)", x = "Treatment")+
    scale_y_continuous(breaks = c(10, 20, 30))+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 3),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          legend.position="none")
#ggsave("Fish_Richness_Years.tiff", width = 23, height = 14, units = "cm", dpi=1200, compression = "lzw")

```

# Biomass & Abundance
## Biomass
### Treatment comparisons
```{r biomass treatment}

# ---- DATA PREP ----
bio <- fish[rowSums(fish[,3:14]) != 0, ] # Remove species not observed in a survey
bio <- bio[bio$Coloured == 12, ] # Remove non-instantaneous data (colored Excel cells)
bio <- select(bio, -c("Coloured"))

## Add info
bio <- merge(bio, surveys, all.x=T, by='SurveyNo')
bio <- merge(bio, specieslist, all.x=T, by='Species')

## Get Size class from wide to long
bio <- reshape2::melt(bio, id.vars = c('SurveyNo', 'Transect', 'Species', 'Diet', 'a', 'b', 'Area'), 
          measure.vars = c('1.25', '3.75', '6.25', '8.75', '12.5', '17.5', '25', '35', '45', '75', '125', '175'),
          variable.name = 'SizeClass', value.name = 'Abundance')

## Cleanup
bio <- bio[bio$Abundance != 0,] # Remove size classes not observed per species (to speed up R)
bio$SizeClass <- as.numeric(paste(bio$SizeClass)) # Set a numeric Length

## Calculate biomass using the length-weight formula W = a * L^b, multiply per abundance and standardize to kg/ha
bio$Biomass_ha <- ((((bio$a * (bio$SizeClass ^ bio$b)) * bio$Abundance)/ bio$Area)/1000)* 10000

## Select
bio.cor <- select(bio, - c("Transect","a", "b")) # Keep area in corrected dataset to recalculate biomass
bio <- select(bio.cor, - c("Area"))

## Make already a grouping, for Ordination analysis on Diet level
bioDiet <- spread(bio, key = Diet, value = Biomass_ha) # Make Diet section from long to wide
bioDiet <- bioDiet[,-c(2:4)] #Remove unnecessary columns
bioDiet[is.na(bioDiet)] <- 0
bioDiet <- merge(bioDiet, totsur, all.y=T) # Re-add surveys without observations
bioDiet[is.na(bioDiet)] <- 0
bioDiet <- aggregate(. ~ SurveyNo, data = bioDiet, FUN = sum) # Sum each Diet per Survey

```

# Biomass treatment
```{r biomass treatment}
## Summarize per survey - Biomass
biosum <- merge(surveys[ ,c(1:6)], bio, by = "SurveyNo", all.x=T)
biosum <- aggregate(Biomass_ha ~ SurveyNo, biosum, sum) # Get the total biomass per survey
biosum <- merge(biosum, totsur, all.y=T) # Re-add surveys without observations
biosum[is.na(biosum)] <- 0
biosum <- merge(surveys[ ,c(1:6)], biosum, by = "SurveyNo", all.x=T)

## Summarize per survey - Abundance
abusum <- merge(surveys[ ,c(1:6)], bio, by = "SurveyNo", all.x=T)
abusum <- aggregate(Abundance ~ SurveyNo, abusum, sum) # Get the total biomass per survey
abusum <- merge(abusum, totsur, all.y=T) # Re-add surveys without observations
abusum[is.na(abusum)] <- 0
abusum <- merge(surveys[ ,c(1:6)], abusum, by = "SurveyNo", all.x=T)

## Aggregate the simultaneous surveys and means for transects per study
biosumsubmeans <- subset(biosum, Observer != "Cindy" & Observer != "Mercy") # Practice
biosumsubmeans <- aggregate(Biomass_ha ~ Transect + Date + Study + ReefType, biosumsubmeans, mean)

## Average per patch
biosumsubtransmeans <- subset(biosum, Observer != "Cindy" & Observer != "Mercy") # Practice
biosumsubtransmeans <- aggregate(Biomass_ha ~ Transect + Study + ReefType, biosumsubtransmeans, mean)

## Add meta data
biosumsubmeans <- merge(biosumsubmeans, metadata, all.x=T)
biosumsubtransmeans <- merge(biosumsubtransmeans,metadata, all.x=T)

# ---- MODELLING ----
# Log-transformed because of heterogeneity residuals
biosumsubmeans$Biomass_ha[biosumsubmeans$Biomass_ha == 0] <- min(biosumsubmeans$Biomass_ha[biosumsubmeans$Biomass_ha>0])/2

## ==== 2021 ====
### Data selection
biosumsubmeans.2021 <- subset(biosumsubmeans, Study == 2021)
biosumsubtransmeans.2021 <- subset(biosumsubtransmeans, Study == 2021)

### Model
lmerBiomeans.2021 <- lmer(log10(Biomass_ha) ~ ReefType + (1|Transect), data = biosumsubmeans.2021)

### Inclusion of Depth as co-variate not helping
AIC(lmer(log10(Biomass_ha)~ Depth_Abs + ReefType+ (1|Transect), data=biosumsubmeans.2021),
    lmer(log10(Biomass_ha)~ ReefType+ (1|Transect), data=biosumsubmeans.2021))

car::Anova(lmerBiomeans.2021)

### Model validation
mod <- lmerBiomeans.2021 # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(biosumsubmeans.2021$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ log10(biosumsubmeans.2021$Biomass_ha)) # response data vs fitted
par(op)

### Post hoc
emmBiomeans.2021 <- emmeans(lmerBiomeans.2021, list(pairwise ~ ReefType), adjust='tukey', type = "response") 
emmBiosum.2021 <- multcomp::cld(emmBiomeans.2021$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE)
emmBiosum.2021 <- emmBiosum.2021 %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

## ==== 2020 ====
### Select data
biosumsubmeans.2020 <- subset(biosumsubmeans, Study == 2020 & !grepl("extra", biosumsubmeans$ReefType))
biosumsubtransmeans.2020 <- subset(biosumsubtransmeans, Study == 2020 & !grepl("extra", biosumsubtransmeans$ReefType))

### Model
lmerBiomeans.2020 <- lmer(log10(Biomass_ha) ~ ReefType + (1|Transect), data = biosumsubmeans.2020)
Anova(lmerBiomeans.2020)

### Model validation
mod <- lmerBiomeans.2020 # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(biosumsubmeans.2020$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ log10(biosumsubmeans.2020$Biomass_ha)) # response data vs fitted
par(op)

### Post hoc
emmBiomeans.2020 <- emmeans(lmerBiomeans.2020, list(pairwise ~ ReefType), adjust='tukey', type = "response") 
emmBiosum.2020 <- multcomp::cld(emmBiomeans.2020$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE)
emmBiosum.2020 <- emmBiosum.2020 %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

## ==== Model 2021 - Coral adjusted? ====
### Create data frame
bioeffects <- biosumsubmeans[biosumsubmeans$Study=='2021',]

### Exclude references (covariates not relevant)
bioeffects <- bioeffects[bioeffects$ReefType!=c('Ref (-)'),]
bioeffects <- bioeffects[bioeffects$ReefType!=c('Ref (+)'),]

### Compare various co-variate models
lmBio <- lmer(log10(Biomass_ha) ~ ReefType+(1|Transect), data=bioeffects)
lmBio0 <- lmer(log10(Biomass_ha) ~ Depth_Abs +ReefType+(1|Transect), data=bioeffects)
lmBio1 <- lmer(log10(Biomass_ha) ~ `AR CC`+ReefType+(1|Transect), data=bioeffects)
lmBio2 <- lmer(log10(Biomass_ha) ~ ARdist+ReefType+(1|Transect), data=bioeffects)
lmBio4 <- lmer(log10(Biomass_ha) ~ Hard.substrate_cor+ReefType+(1|Transect), data=bioeffects)
lmBio5 <- lmer(log10(Biomass_ha) ~ Reefdist+ReefType+(1|Transect), data=bioeffects)
lmBioall <- lmer(log10(Biomass_ha)~`AR CC`+ARdist+Hard.substrate_cor+Reefdist+ReefType+(1|Transect), data=bioeffects)
Anova(lmBioall)

AIC(lmBio,lmBio0, lmBio1, lmBio2, lmBio4, lmBio5, lmBioall) #Best model includes (only) AR coral cover (lmBio1)
lmerBiomeanscor <- lmBio1 # Set final model

Anova(lmerBiomeanscor)
### Positive effect of Hard coral on Fish Biomass
summary(lmerBiomeanscor)

### Validation
mod <- lmerBiomeanscor # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(bioeffects$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(bioeffects$Study, resid(mod, type = "pearson")) # residuals split over Treatment
abline(0,0)
plot(fitted(mod) ~ log10(bioeffects$Biomass_ha)) # response data vs fitted
par(op)

### Post hoc: no differences between ARs
emmBiocor2 <- emmeans(lmerBiomeanscor, specs=pairwise ~ ReefType, adjust= 'tukey')

## ==== Throughout the years ====
biosumsubmeans.years <- subset(biosumsubmeans, (ReefType == "Ref (-)" | ReefType == "Ref (+)") & (Study != 2018))
biosumsubtransmeans.years <- subset(biosumsubtransmeans, (ReefType == "Ref (-)" | ReefType == "Ref (+)") & (Study != 2018))

### Model
lmerBiomeancor.years <- lmer(log10(Biomass_ha) ~ ReefType*Study + (1|Transect), data = biosumsubmeans.years)

Anova(lmerBiomeancor.years)
summary(lmerBiomeancor.years)

### Model validation
mod <- lmerBiomeancor.years # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(biosumsubmeans.years$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(biosumsubmeans.years$Study, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ log10(biosumsubmeans.years$Biomass_ha)) # response data vs fitted
par(op)

## Post hoc
### Treatment * Year + Compact Letter Display
emmBiocor.years <- emmeans(lmerBiomeancor.years, specs = pairwise ~ Study|ReefType,
                           adjust = 'tukey', type = "response") 
emmBiocorsum.years <- multcomp::cld(emmBiocor.years$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE)
emmBiocorsum.years <- emmBiocorsum.years %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# ---- PLOTS ----

## ==== 2021  ====
### Biomass 2021 (no depth-adjusting needed)
Bioplot <- ggplot(data = biosumsubtransmeans.2021, aes(x = ReefType, y = Biomass_ha, colour = ReefType))+
    geom_jitter(width = 0.2, size = 2)+
    scale_colour_manual(values = co)+
    scale_x_discrete(expand = c(0, 0.7), labels=c("Bottle", "Cage", "Cake", "Compound", "Control", "Reference"))+
    geom_point(data= emmBiosum.2021, aes(y = response), colour = 'black', size = 4)+
    geom_errorbar(data = emmBiosum.2021, width = 0.1, colour='black', size=0.8,
                  aes(y = response, ymin = response - SE, ymax = response + SE))+
    geom_text(data=emmBiosum.2021, aes(label = .group, y = response + 3.5*SE), colour = 'black', size = 7)+
    labs(y = expression(paste("Fish biomass (kg ", ha^-1,")")), x = "Treatment")+
    scale_y_continuous(trans = 'log10', breaks = c(10, 100, 1000))+
    coord_cartesian(ylim = c(4, 1001))+
    scale_color_manual(values=co)+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 2.7),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_text(size = 14, face = "plain", vjust = -0.5),
          axis.text.x = element_text(size = 12, face = "bold", vjust = 0.5),
          legend.position="none")

## ==== 2020  ====
### Biomass 2020
ggplot(data = biosumsubtransmeans.2020, aes(x = ReefType, y = Biomass_ha, colour = ReefType))+
    geom_jitter(width = 0.2, size = 2)+
    geom_point(data= emmBiosum.2020, aes(y = response), colour = 'black', size = 4)+
    geom_errorbar(data = emmBiosum.2020, width = 0.1, colour='black', size=0.8,
                  aes(y = response, ymin = response - SE, ymax = response + SE))+
    geom_text(data=emmBiosum.2020, aes(label = .group, y = response + 2*SE), colour = 'black', size = 7)+
    labs(y = expression(paste("Fish biomass kg ( ", ha^-1,")")), x = "Treatment")+
    scale_y_continuous(trans = 'log10', breaks = c(1, 10, 100, 1000))+
    coord_cartesian(ylim = c(1, 1001))+
    scale_color_manual(values=co)+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 3),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_text(size = 14, face = "plain", vjust = -0.5),
          axis.text.x = element_text(size = 14, face = "bold", vjust = 0.5))
#ggsave("Fish_Biomass_2020.tiff", width = 23, height = 14, units = "cm", dpi=1200, compression = "lzw")

## ==== Throughout the Years ====
biosumsubtransmeans.years$ReefType <- ifelse(biosumsubtransmeans.years$ReefType == "Ref (-)", "Control", 
                                      ifelse(biosumsubtransmeans.years$ReefType == "Ref (+)", "Reference", "Other"))
emmBiocorsum.years$ReefType <- ifelse(emmBiocorsum.years$ReefType == "Ref (-)", "Control", 
                                      ifelse(emmBiocorsum.years$ReefType == "Ref (+)", "Reference", "Other"))

### Biomass throughout the years plot
bio.years <- ggplot(data = biosumsubtransmeans.years, aes(x = Study, colour = ReefType, y = Biomass_ha))+
    facet_grid(.~ReefType)+
    geom_jitter(width = 0.2, size = 2)+
    geom_point(data = emmBiocorsum.years, aes(y = response), size = 4, colour='black')+
    geom_errorbar(data = emmBiocorsum.years, width = 0.1, colour='black', size=0.8,
                  aes(y = response, ymin = response - SE, ymax = response + SE))+
    geom_text(data=emmBiocorsum.years, 
              aes(label = .group, y = response + 3*SE), colour = 'black', size = 7)+
    labs(y = expression(paste("Fish biomass (kg ", ha^-1,")")), x = "Year")+
    scale_y_continuous(trans = 'log10', breaks = c(1, 10, 100, 1000))+
    scale_x_discrete(labels=c('2019', '2020', '2022'))+
    coord_cartesian(ylim = c(1, 1001))+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 2.7),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_text(size = 14, face = "plain", vjust = -0.5),
          axis.text.x = element_text(size = 14, face = "bold", vjust = 0.5),
          legend.position="none")
#ggsave("Fish_Biomass_Years.tiff", width = 23, height = 14, units = "cm", dpi=1200, compression = "lzw")

```

# Biomass treatment - Corrected
```{r biomass treatment corrected}

## Summarize per survey - Biomass - Corrected for ARea
biosum.cor <- merge(surveys[ ,c(1:6)], bio.cor, by = "SurveyNo", all.x=T)
### Recalculate biomass assuming only 6x6 m2 plot is relevant for ARs
biosum.cor$Biomass_ha <- ifelse(grepl("Ref", biosum.cor$ReefType), biosum.cor$Biomass_ha,    (biosum.cor$Biomass_ha/32)*biosum.cor$Area)
biosum.cor <- aggregate(Biomass_ha ~ SurveyNo, biosum.cor, sum) # Get the total biomass per survey
biosum.cor <- merge(biosum.cor, totsur, all.y=T) # Re-add surveys without observations
biosum.cor[is.na(biosum.cor)] <- 0
biosum.cor <- merge(surveys[ ,c(1:6)], biosum.cor, by = "SurveyNo", all.x=T)

## Aggregate the simultaneous surveys and means for transects per study - corrected
biosumsubmeans.cor <- subset(biosum.cor, Observer != "Cindy" & Observer != "Mercy") # Practice
biosumsubmeans.cor <- aggregate(Biomass_ha ~ Transect + Date + Study + ReefType, biosumsubmeans.cor, mean) 

## Average per patch - Corrected
biosumsubtransmeans.cor <- subset(biosum.cor, Observer != "Cindy" & Observer != "Mercy") # Practice
biosumsubtransmeans.cor <- aggregate(Biomass_ha ~ Transect + Study + ReefType, biosumsubtransmeans.cor, mean) 

## Add meta data - Corrected
biosumsubmeans.cor <- merge(biosumsubmeans.cor, metadata, all.x=T)
biosumsubtransmeans.cor <- merge(biosumsubtransmeans.cor, metadata, all.x=T)

# ---- MODELLING ----
# Log-transformed because of heterogeneity residuals
biosumsubmeans.cor$Biomass_ha[biosumsubmeans.cor$Biomass_ha == 0] <- min(biosumsubmeans.cor$Biomass_ha[biosumsubmeans.cor$Biomass_ha>0])/2

## ==== 2021 ====
### Data selection
biosumsubmeans.2021.cor <- subset(biosumsubmeans.cor, Study == 2021)
biosumsubtransmeans.2021.cor <- subset(biosumsubtransmeans.cor, Study == 2021)

### Model
lmerBiomeans.2021.cor <- lmer(log10(Biomass_ha) ~ ReefType + (1|Transect), data = biosumsubmeans.2021.cor)

### Inclusion of Depth as co-variate not helping
AIC(lmer(log10(Biomass_ha)~ Depth_Abs + ReefType+ (1|Transect), data=biosumsubmeans.2021.cor),
    lmer(log10(Biomass_ha)~ ReefType+ (1|Transect), data=biosumsubmeans.2021.cor))

Anova(lmerBiomeans.2021.cor)

### Model validation
mod <- lmerBiomeans.2021.cor # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(biosumsubmeans.2021.cor$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ log10(biosumsubmeans.2021.cor$Biomass_ha)) # response data vs fitted
par(op)

### Post hoc
emmBiomeans.2021.cor <- emmeans(lmerBiomeans.2021.cor, list(pairwise ~ ReefType), adjust='tukey', type = "response") 
emmBiosum.2021.cor <- multcomp::cld(emmBiomeans.2021.cor$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE)
emmBiosum.2021.cor <- emmBiosum.2021.cor %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# ---- PLOTS ----

## ==== 2021  ====
### Biomass 2021 (no depth-adjusting needed)
bio.cor <- ggplot(data = biosumsubtransmeans.2021.cor, aes(x = ReefType, y = Biomass_ha, colour = ReefType))+
    geom_jitter(width = 0.2, size = 2)+
    scale_colour_manual(values = co)+
    scale_x_discrete(labels=c("Bottle", "Cage", "Cake", "Compound", "Control", "Reference"))+
    geom_point(data= emmBiosum.2021.cor, aes(y = response), colour = 'black', size = 4)+
    geom_errorbar(data = emmBiosum.2021.cor, width = 0.1, colour='black', size=0.8,
                  aes(y = response, ymin = response - SE, ymax = response + SE))+
    geom_text(data=emmBiosum.2021.cor, aes(label = .group, y = response + 4*SE), colour = 'black', size = 7)+
    labs(y = expression(paste("Fish biomass (kg ", ha^-1,")")), x = "Treatment")+
    scale_y_continuous(trans = 'log10', breaks = c(1, 10, 100, 1000, 10000))+
    coord_cartesian(ylim = c(1, 10000))+
    scale_color_manual(values=co)+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 2.7),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_text(size = 14, face = "plain", vjust = -0.5),
          axis.text.x = element_text(size = 12, face = "bold", vjust = 0.5),
          legend.position="none")
#ggsave("Fish_Biomass_ARea corrected.tiff", width = 23, height = 14, units = "cm", dpi=1200, compression = "lzw")

# Summary values
biosumsubtransmeans.2021.cor.avg <- data_summary(biosumsubtransmeans.2021.cor, varname = "Biomass_ha", groupnames = c("ReefType"))

```

### Composition comparisons
<!--
Composition comparisons done on Biomass level, because more informative than on Abundance level
-->
```{r biomass composition}

# ---- DATA PREP ----
## ==== Species ====
### Create data frame
bio.ord <- spread(bio, key = Species, value = Biomass_ha) # Wide to long
bio.ord <- select(bio.ord, -c(2:4))
bio.ord[is.na(bio.ord)] <- 0
bio.ord <- aggregate(. ~ SurveyNo, data = bio.ord, FUN = sum, na.action = na.omit) # Sum each Species per Survey

### Add info and re-add surveys without observations
bio.ord <- left_join(surveys[, c(1:6)], bio.ord, by = "SurveyNo")

### Data selection
bio.ord[is.na(bio.ord)] <- 0 # Set all Species to 0 for surveys without observations

## Select subsets
bio.ord.years <- subset(bio.ord, ReefType == "Ref (+)" & Study != 2018)
bio.ord <- subset(bio.ord, Study == 2021 & Observer == "Jelle Rienstra")

### average over replicate surveys
bio.ord <- aggregate(.~Transect+ReefType+Study, bio.ord, mean)
bio.ord.years <- aggregate(.~Transect+ReefType+Study, bio.ord.years, mean)

## ==== Diet ====
### Create data frame
bioBrayDiet <- merge(surveys[, c(1:6)], bioDiet, all.x=T)

### Data selection
bioBrayDiet <- subset(bioBrayDiet, Study == 2021 & Observer == "Jelle Rienstra")

### Average over replicate surveys
subbcDiet.bio <- aggregate(.~Transect+ReefType+Study, bioBrayDiet, mean)

# ---- STATS ----

## ==== Species ====
### #### 2021 ####
#### Create a bc mean distance table 
BCtable.Bio.Specs <- vegdist(bio.ord[,7:ncol(bio.ord)], "bray")
BCtable.Bio.Specs.tab <- as.data.frame(meandist(BCtable.Bio.Specs, bio.ord$ReefType, cluster=average))

#### Stats
adonis.Bio.Specs <- adonis2(formula = BCtable.Bio.Specs ~ ReefType, data = bio.ord, permutations = 9999)
pairadonis.Bio.Specs <- pairwise.adonis(BCtable.Bio.Specs, bio.ord$ReefType, p.adjust='bonferroni', perm = 37000)

#### NMDS
NMDS.Bio.Spec <- metaMDS(bio.ord[,7:ncol(bio.ord)], distance = "bray", k = 2, trymax=3000, autotransform = FALSE) 

### #### Years ####
BCtable.Bio.Specs.years <- vegdist(bio.ord.years[,7:ncol(bio.ord.years)], "bray")

#### Stats
adonis.Bio.Specs.years <- adonis2(formula = BCtable.Bio.Specs.years ~ Study,
                                  data = bio.ord.years, permutations = 9999)
pairadonis.Bio.Specs.years <- pairwise.adonis(BCtable.Bio.Specs.years, bio.ord.years$Study,
                                              p.adjust='bonferroni', perm = 37000)

#### NMDS
NMDS.Bio.Spec.years <- metaMDS(bio.ord.years[,7:ncol(bio.ord.years)],
                               distance = "bray", k = 2, trymax=3000, autotransform = FALSE) 

## ==== Diet ====
### Create a bc mean distance table 
BCtable.Bio.Diet <- vegdist(subbcDiet.bio[,7:ncol(subbcDiet.bio)], "bray")
BCtable.Bio.Diet.tab <- as.data.frame(meandist(BCtable.Bio.Diet, subbcDiet.bio$ReefType, cluster=average))

### Stats
adonis.Bio.Diet <- adonis2(formula = BCtable.Bio.Diet ~ ReefType, data = subbcDiet.bio, permutations = 9999)
pairadonis.Bio.Diet <- pairwise.adonis(BCtable.Bio.Diet, subbcDiet.bio$ReefType, p.adjust = 'bonferroni', perm = 37000)

### NMDS
NMDS.Bio.Diet <- metaMDS(subbcDiet.bio[,7:ncol(subbcDiet.bio)], distance = "bray", k = 2, trymax=1000, autotransform = FALSE) 

## ==== Years (Abundance) ====
### Create a bc mean distance table 
#### Ref (-)
Specs.sum.min <- subset(Specs.sum, ReefType == "Ref (-)")
BCtable.Abu.Years <- vegdist(Specs.sum.min[,3:ncol(Specs.sum.min)], "bray")
BCtable.Abu.Years.tab <- as.data.frame(meandist(BCtable.Abu.Years, Specs.sum.min$Study, cluster=average))

### Stats
adonis.Abu.Years <- adonis2(formula = BCtable.Abu.Years ~ Study, data = Specs.sum.min, permutations = 9999)
pairadonis.Abu.Years <- pairwise.adonis(BCtable.Abu.Years, Specs.sum.min$Study, p.adjust = 'bonferroni', perm = 37000)

### NMDS
NMDS.Abu.Years <- metaMDS(Specs.sum.min[,3:ncol(Specs.sum.min)], distance = "bray", k = 2, trymax=1000, autotransform = FALSE)

#### Ref (+)
Specs.sum.plus <- subset(Specs.sum, ReefType == "Ref (+)")
BCtable.Abu.Years.plus <- vegdist(Specs.sum.plus[,3:ncol(Specs.sum.plus)], "bray")
BCtable.Abu.Years.tab.plus <- as.data.frame(meandist(BCtable.Abu.Years.plus, Specs.sum.plus$Study, cluster=average))

### Stats
adonis.Abu.Years.plus <- adonis2(formula = BCtable.Abu.Years.plus ~ Study, data = Specs.sum.plus, permutations = 9999)
pairadonis.Abu.Years.plus <- pairwise.adonis(BCtable.Abu.Years.plus, Specs.sum.plus$Study, p.adjust = 'bonferroni', perm = 37000)

### NMDS
NMDS.Abu.Years.plus <- metaMDS(Specs.sum.plus[,3:ncol(Specs.sum.plus)], distance = "bray", k = 2, trymax=1000, autotransform = FALSE) 


# ---- PLOTS ----

## ==== Species ====
#### 2021 ####
##### On Patch level
NMDS.Bio.Spec.Patch <- as.data.frame(scores(NMDS.Bio.Spec, display="site"))
NMDS.Bio.Spec.Patch$Treatment <- subbcDiet.bio$ReefType
NMDS.Bio.Spec.Patch$Interaction <- subbcDiet.bio$Interaction

Ordi.Sp.Patch <- ggplot(data = NMDS.Bio.Spec.Patch)+
    stat_ellipse(geom = "polygon", alpha = 0.1, aes(x = NMDS1, y = NMDS2, fill = Treatment),
                level = 0.5, size = 12)+
    scale_fill_manual(values=co)+
    geom_point(aes(x = NMDS1,y = NMDS2, colour = Treatment), size= 2)+
    scale_color_manual(values=co)+
    scale_y_continuous(limits = c(-2, 2), breaks = c(-2, 0, 2))+
    theme_bw()+
    theme(legend.position = "none",
          legend.text = element_text(size = 12),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.title.y = element_text(size = 14, face = "plain", vjust = 3),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          plot.margin = margin(0, 0, 0.2, 0.5, "cm"),
          axis.ticks.length.x = unit(0, "cm"))
#ggsave("Fish_Ordination species_Patch_Biomass.tiff", width = 18, height = 14, units = "cm", dpi=1200, compression = "lzw")

#### On Species level
##### Adjust font size based on % of surveys in which a species is seen
specsizes.bio <- bio.ord[,7:ncol(bio.ord)]
specsizes.bio <- colSums(specsizes.bio)
specsizes.bio.min <- min(specsizes.bio)
specsizes.bio.max <- max(specsizes.bio)
cex.bio.min <- 0.05
cex.bio.max <- 2
specsizes.bio <- ((specsizes.bio - specsizes.bio.min)/(specsizes.bio.max-specsizes.bio.min)) * (cex.bio.max - cex.bio.min) + cex.bio.min

##### Plot on Species level
##### For composite
cox <- c(co, "#0673B0", "#0673B0", "#0673B0") # Strangely: original colour palette wasn't working here

pdf(NULL)
dev.control(displaylist="enable")
par(bg = 'white',   las=1, tck=-0.007, cex.axis=1.1, cex.lab = 1.1, font.axis = 2, mar=c(6.5, 4.2, 0.1, 0.2), 
    col.axis = "#464646")
ordiplot(NMDS.Bio.Spec, type="none",  cex = 0.3, ylim = c(-1.1, 1.1), xlim = c(-0.1, 0.9))
ordiellipse(NMDS.Bio.Spec, groups = bio.ord$ReefType, kind = "se", conf = 0.99, draw  ="polygon", 
            col = cox, alpha = 50, label = F, lty = 'blank', border = "white")
ordipointlabel(NMDS.Bio.Spec, display = "species", scaling = "symmetric", add = TRUE,
               cex = specsizes.bio, font = 3)
Ordi.Sp.Sp <- recordPlot()
invisible(dev.off())
#Ordi.Sp.Sp <- plot_grid(Ordi.Sp.Sp) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))

#### Years ####
#### Ref (+) Biomass
##### Adjust font size based on % of surveys in which a species is seen
specsizes.bio.years <- bio.ord.years[,7:ncol(bio.ord.years)]
specsizes.bio.years <- colSums(specsizes.bio.years)
specsizes.bio.years.min <- min(specsizes.bio.years)
specsizes.bio.years.max <- max(specsizes.bio.years)
cex.bio.years.min <- 0.03
cex.bio.years.max <- 2
specsizes.bio.years <- ((specsizes.bio.years - specsizes.bio.years.min)/(specsizes.bio.years.max-specsizes.bio.years.min)) * (cex.bio.years.max - cex.bio.years.min) + cex.bio.years.min

##### Plot on Species*Study level
tiff("Fish_Ordination species_Species_Years_Biomass.tiff", width = 18, height = 14, units = "cm", res = 1200, compression = "lzw")
Ordi.Sp.Sp.years <- ordiplot(NMDS.Bio.Spec.years, type="none",
                             cex = 0.3, ylim = c(-0.3, 0.2), xlim = c(-1.8, 2.1))
ordiellipse(NMDS.Bio.Spec.years, groups = bio.ord.years$Study, kind = "se", conf = 0.99, draw  ="polygon", 
            col = c("#fff07c", "#f2b037", "#fb7600", "#dd3434"), alpha = 50, label = T, lty = 'blank', border = "white")
ordipointlabel(NMDS.Bio.Spec.years, display = "species", scaling = 9, add = TRUE, cex = specsizes.bio.years)
dev.off()

#### Ref (-) Abundance
##### Adjust font size based on % of surveys in which a species is seen
specsizes.abu.years <- Specs.sum.min[,3:ncol(Specs.sum.min)]
specsizes.abu.years <- colSums(specsizes.abu.years)
Specs.sum.min.min <- min(specsizes.abu.years)
Specs.sum.min.max <- max(specsizes.abu.years)
cex.abu.years.min <- 0.03
cex.abu.years.max <- 2
specsizes.abu.years <- ((specsizes.abu.years - cex.abu.years.min)/(Specs.sum.min.max-Specs.sum.min.min)) * (cex.abu.years.max - cex.abu.years.min) + cex.abu.years.min

##### Plot on Species*Study level
#tiff("Fish_Ordination species_Species_Years_Abundance.tiff", width = 18, height = 14, units = "cm", res = 1500, compression = "lzw")
Ordi.Sp.Sp.years.abu <- ordiplot(NMDS.Abu.Years, type="none",
                             cex = 0.3, ylim = c(-0.3, 0.2), xlim = c(-1.8, 2.1))
ordiellipse(NMDS.Abu.Years, groups = Specs.sum.min$Study, kind = "se", conf = 0.99, draw  ="polygon", 
            col = c("#fff07c", "#fb7600", "#dd3434"), alpha = 50, label = T, lty = 'blank', border = "white")
ordipointlabel(NMDS.Abu.Years, display = "species", scaling = 9, add = TRUE, cex = specsizes.abu.years)
#dev.off()

#### Ref (+) Abundance
##### Adjust font size based on % of surveys in which a species is seen
specsizes.abu.years.plus <- Specs.sum.plus[,3:ncol(Specs.sum.plus)]
specsizes.abu.years.plus <- colSums(specsizes.abu.years.plus)
Specs.sum.plus.min <- min(specsizes.abu.years.plus)
Specs.sum.plus.max <- max(specsizes.abu.years.plus)
cex.abu.years.plus.min <- 0.03
cex.abu.years.plus.max <- 2
specsizes.abu.years.plus <- ((specsizes.abu.years.plus - cex.abu.years.plus.min)/(Specs.sum.plus.max-Specs.sum.plus.min)) * (cex.abu.years.plus.max - cex.abu.years.plus.min) + cex.abu.years.plus.min

##### Plot on Species*Study level
#tiff("Fish_Ordination species_Species_Years_Abundance.plus.tiff", width = 18, height = 14, units = "cm", res = 1500, compression = "lzw")
Ordi.Sp.Sp.years.abu.plus <- ordiplot(NMDS.Abu.Years.plus, type="none",
                             cex = 0.3, ylim = c(-0.3, 0.2), xlim = c(-1.8, 2.1))
ordiellipse(NMDS.Abu.Years.plus, groups = Specs.sum.plus$Study, kind = "se", conf = 0.99, draw  ="polygon", 
            col = c("#fff07c", "#fb7600", "#dd3434"), alpha = 50, label = T, lty = 'blank', border = "white")
ordipointlabel(NMDS.Abu.Years.plus, display = "species", scaling = 9, add = TRUE, cex = specsizes.abu.years.plus)
#dev.off()

## ==== Diet ====
### On Patch level
NMDS.Bio.Diet.Patch <- as.data.frame(scores(NMDS.Bio.Diet, display="site"))
NMDS.Bio.Diet.Patch$Treatment <- ifelse(subbcDiet.bio$ReefType == "BRU", "Bottle",
                                 ifelse(subbcDiet.bio$ReefType == "Cage", "Cage",       
                                 ifelse(subbcDiet.bio$ReefType == "Cake", "Cake",       
                                 ifelse(subbcDiet.bio$ReefType == "Comp", "Compound",       
                                 ifelse(subbcDiet.bio$ReefType == "Ref (-)", "Control",      
                                 ifelse(subbcDiet.bio$ReefType == "Ref (+)", "Reference", "Other"))))))

Ordi.Diet.Patch <- ggplot(data = NMDS.Bio.Diet.Patch)+
    stat_ellipse(geom = "polygon", alpha = 0.1, aes(x = NMDS1, y = NMDS2, fill = Treatment),
                level = 0.6, size = 10)+ # Not an actual confidence ellipse, but matches that of ordiplot
    scale_fill_manual(values=co)+
    geom_point(aes(x = NMDS1,y = NMDS2, colour = Treatment), size= 2)+
    scale_color_manual(values=co)+
    scale_y_continuous(breaks = c(-1, 0, 1), limits = c(-1, 1))+
    scale_x_continuous(limits = c(-2, 2))+
    theme_bw()+
    theme(legend.text = element_text(size = 12),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.title.y = element_text(size = 14, face = "plain", vjust = 3),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_text(size = 14, face = "plain", vjust = -0.5),
          axis.text.x = element_text(size = 14, face = "bold", vjust = 0.5),
          legend.position="bottom",
          legend.title = element_blank(),
          plot.margin = margin(0, 0, 0.1, 0.5, "cm"))+
     guides(fill = guide_legend(nrow = 1))
leg <- get_legend(Ordi.Diet.Patch)
#ggsave("Fish_Ordination diet_Patch_Biomass.tiff", width = 18, height = 10, units = "cm", dpi=1200, compression = "lzw")

#### On Species level
##### Adjust font size based on % of surveys in which a species is seen
specsizes.bio.diet <- subbcDiet.bio[,7:ncol(subbcDiet.bio)]
specsizes.bio.diet <- colSums(specsizes.bio.diet)
specsizes.bio.diet.min <- min(specsizes.bio.diet)
specsizes.bio.diet.max <- max(specsizes.bio.diet)
cex.bio.diet.min <- 1
cex.bio.diet.max <- 2
specsizes.bio.diet <- ((specsizes.bio.diet - specsizes.bio.diet.min)/(specsizes.bio.diet.max-specsizes.bio.diet.min)) * (cex.bio.diet.max - cex.bio.diet.min) + cex.bio.diet.min

##### Plot on Species level
##### For composite
cox.diet <- c(co, "#0673B0", "#0673B0", "#0673B0") # Strangely: original colour palette wasn't working here

pdf(NULL)
dev.control(displaylist="enable")
par(bg = 'white',   las=1, tck=-0.007, cex.axis=1.1, cex.lab = 1.1, font.axis = 2, mar=c(4.5, 4.2, 0.1, 0.2), 
    col.axis = "#464646")
ordiplot(NMDS.Bio.Diet, type="none",  cex = 0.3, ylim = c(-0.5, 0.5), xlim = c(-1.9, 2.2))
ordiellipse(NMDS.Bio.Diet, groups = subbcDiet.bio$ReefType, kind = "se", conf = 0.99, draw  ="polygon", 
            col = cox.diet, alpha = 50, label = F, lty = 'blank', border = "white")
ordipointlabel(NMDS.Bio.Diet, display = "species", scaling = "symmetric", add = TRUE,
               cex = specsizes.bio.diet, font = 3)
Ordi.Diet.Sp <- recordPlot()
invisible(dev.off())
#Ordi.Diet.Sp <- plot_grid(Ordi.Diet.Sp) + theme(plot.margin = unit(c(0, 0, 0, 0), "cm"))
#ggsave("Fish_Ordination_Diet by group.tiff", width = 18, height = 12, units = "cm", dpi=1200, compression = "lzw", Ordi.Diet.Sp)

## ==== Composite ====
#ORDI <- plot_grid(Ordi.Sp.Sp, Ordi.Sp.Patch, Ordi.Diet.Patch,  nrow = 3, align = "v", rel_heights = c(1,1,1.3),
   #               labels = c("A: Species", "B: Patch", "C: Diet"),
   #               hjust = c(-0.8, -1, -1.25), vjust = 1.6)
#ggsave("Fish_Ordination_Compilation.tiff", width = 18, height = 24, units = "cm", dpi=1200, compression = "lzw", ORDI)

# TODO: remove large white space in between?!?
ORDI2 <- plot_grid(Ordi.Sp.Sp, Ordi.Diet.Sp,  leg,  nrow = 3,  rel_heights = c(1.2,0.8,0.1),
                  labels = c("A: Species", "B: Diet", ""), align = "hv", greedy = F,
                  hjust = c(-1, -1.6, 0), vjust = c(2, 2, 0))
ggsave("Fish_Ordination_Compilation2.tiff", width = 18, height = 24, units = "cm", dpi=1200, compression = "lzw", ORDI2)



##### High res Species plot
#tiff("Fish_Ordination species_Species_Biomass_Highres.tiff", width = 18, height = 14, units = "cm", res = 3500, compression = "lzw")
#Ordi.Sp.Sp
#dev.off()

```

### BC tables
```{r table}
# ---- TABLE WORD CODE ----
# create new word document
new.word.doc=function(){
  my.doc=read_docx()
  return(my.doc)
}

# add an empty line
add.empty.line=function(doc){
  body_add_par(doc, " ")
  return("empty line added")
}

# add a data frame as a table
add.table=function(doc, tbl, col.keys=NULL, col.digits=NULL){
  # create basic flextable
  f.table=qflextable(tbl)
  
  # set table borders
  f.table=border_inner_h(f.table, part="header", border=fp_border(color="black", width = 1))
  #f.table=border_inner_v(f.table, part="all", border=fp_border(color="black", width = 1))
  
  # set fonts
  f.table=flextable::font(f.table,  fontname = "Times", part = "all")
  # also set the table's header font as bold
  f.table=bold(f.table, part = "header")
  
  # add the table to the document
  flextable::body_add_flextable(doc, 
                                value = f.table, 
                                align = "left" )
  return("table added")
}

# SPECIES
doc=new.word.doc()
add.empty.line(doc)
add.table(doc, BCtable.Bio.Specs.tab)

# generate the Word document using the print function
base::print(doc, target="Fish_BC Table Species x Treatment.docx")

# DIET
doc=new.word.doc()
add.empty.line(doc)
add.table(doc, BCtable.Bio.Diet.tab)

# generate the Word document using the print function
base::print(doc, target="Fish_BC Table Diet x Treatment.docx")

```

## Abundance
### Treatment comparisons
```{r abundance treatment}

# ---- MODELLING ----

## ==== Model 2020-2021 ====
### Prep data
abusumsubmeans <- merge(surveys[ ,c(1,9)], abusum, by = "SurveyNo", all.x=T)
abusumsubmeans$Abundance_m2 <- abusumsubmeans$Abundance / abusumsubmeans$Area 
abusumsubmeans <- aggregate(Abundance_m2 ~ Transect + Date + Study + ReefType, abusumsubmeans, mean) # Mean simul surveys
abusumsubtransmeans <- aggregate(Abundance_m2 ~ Transect + Study + ReefType, abusumsubmeans, mean) # Mean per Patch

### Add meta
abusumsubmeans <- merge(abusumsubmeans, metadata, all.x=T)
abusumsubtransmeans <- merge(abusumsubtransmeans, metadata, all.x=T)

### Modelling
#### Prior analysis showed that depth as co-viarate doesn't improve model
#### Log-transformed because of heterogeneity residuals
abusumsubmeans$Abundance_m2[abusumsubmeans$Abundance_m2 == 0] <- min(abusumsubmeans$Abundance_m2[abusumsubmeans$Abundance_m2>0])/2

## ==== 2021 - not adjusted =====
### Select data
abusumsubmeans.2021 <- subset(abusumsubmeans, Study == 2021)
abusumsubtransmeans.2021 <- subset(abusumsubtransmeans, Study == 2021)

### Model
lmerAbumeans.2021 <- lmer(log10(Abundance_m2) ~ ReefType + (1|Transect), data = abusumsubmeans.2021)
car::Anova(lmerAbumeans.2021)

### Validation
mod <- lmerAbumeans.2021 # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(abusumsubmeans.2021$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ log10(abusumsubmeans.2021$Abundance_m2)) # response data vs fitted
par(op)

### Post hoc
emmAbu.2021 <- emmeans(lmerAbumeans.2021, list(pairwise ~ ReefType), adjust='tukey', type = "response")
emmAbusum.2021 <- multcomp::cld(emmAbu.2021$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE) # get CLD
emmAbusum.2021 <- emmAbusum.2021 %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

## ==== Model 2021 - coral adjusted ====
### Data prep
abueffects <- subset(abusumsubmeans, Study == 2021)

### Exclude references (covariates not relevant)
abueffects <- abueffects[abueffects$ReefType!=c('Ref (-)'),]
abueffects <- abueffects[abueffects$ReefType!=c('Ref (+)'),]

### Compare various covariates
lmAbu  <- lmer(log10(Abundance_m2) ~ ReefType+(1|Transect), data=abueffects)
lmAbu0 <- lmer(log10(Abundance_m2) ~ Depth_Abs +ReefType+(1|Transect), data=abueffects)
lmAbu1 <- lmer(log10(Abundance_m2) ~ `AR CC` + ReefType + (1|Transect), data=abueffects)
lmAbu2 <- lmer(log10(Abundance_m2) ~ ARdist+ReefType+(1|Transect), data=abueffects)
lmAbu4 <- lmer(log10(Abundance_m2) ~ Hard.substrate_cor+ReefType+(1|Transect), data=abueffects)
lmAbu5 <- lmer(log10(Abundance_m2) ~ Reefdist+ReefType+(1|Transect), data=abueffects)
lmAbuall <- lmer(log10(Abundance_m2)~`AR CC`+ARdist+Hard.substrate_cor+Reefdist+ReefType+(1|Transect), data=abueffects)
Anova(lmAbuall)

AIC(lmAbu,lmAbu0, lmAbu1, lmAbu2, lmAbu4, lmAbu5, lmAbuall) #Best model (by far) includes (only) AR coral cover

lmerAbumeanscor <- lmAbu1 # Set as final model

### Results
Anova(lmerAbumeanscor)
### Positive effect Hard coral on Abundance
summary(lmerAbumeanscor)

### Validation
mod <- lmerAbumeanscor # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(abueffects$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(abueffects$Study, resid(mod, type = "pearson")) # residuals split over Treatment
abline(0,0)
plot(fitted(mod) ~ log10(abueffects$Abundance_m2)) # response data vs fitted
par(op)

### Post hoc
emmAbucor <- emmeans(lmerAbumeanscor, specs = pairwise ~ ReefType, adjust='tukey')

## ==== Throughout the years ====
abusumsubmeans.years <- subset(abusumsubmeans, (ReefType == "Ref (-)" | ReefType == "Ref (+)") & (Study != 2018))
abusumsubtransmeans.years <- subset(abusumsubtransmeans, (ReefType == "Ref (-)" | ReefType == "Ref (+)") & (Study != 2018))

### Model
lmerAbumeancor.years <- lmer(log10(Abundance_m2) ~ ReefType*Study + (1|Transect), data = abusumsubmeans.years)

Anova(lmerAbumeancor.years)
summary(lmerAbumeancor.years)

### Model validation
mod <- lmerAbumeancor.years # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(abusumsubmeans.years$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(abusumsubmeans.years$Study, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ log10(abusumsubmeans.years$Abundance_m2)) # response data vs fitted
par(op)

## Post hoc
### Treatment * Year + Compact Letter Display
emmAbucor.years <- emmeans(lmerAbumeancor.years, specs = pairwise ~ Study|ReefType, adjust = 'tukey', type = "response") 
emmAbucorsum.years <- multcomp::cld(emmAbucor.years$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE) # get CLD
emmAbucorsum.years <- emmAbucorsum.years %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces

# ---- PLOTS ----

## ==== 2021 - not adjusted ====
### Abundance 2021 - not adjusted
Abuplot <- ggplot(data = abusumsubtransmeans.2021, aes(x = ReefType, colour = ReefType, y = Abundance_m2))+ 
    geom_jitter(width = 0.2, size = 2)+
    geom_point(data= emmAbusum.2021, aes(y = response), colour = 'black', size = 4)+
    geom_errorbar(data = emmAbusum.2021, width = 0.1, colour='black', size=0.8,
                  aes(y = response, ymin = response - SE, ymax = response + SE))+
    geom_text(data=emmAbusum.2021, 
              aes(label = .group, y = response + 3.5*SE), colour = 'black', size = 7)+
    labs(y = expression(paste("Fish abundance ( ", m^-2,")")), x = "Treatment")+
    scale_y_continuous(trans = 'log10', breaks = c(0.1, 1, 10))+
    coord_cartesian(ylim = c(0.05, 11))+
    scale_color_manual(values=co)+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 2.7),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          legend.position="none")

## ==== Throughout the Years ====
abusumsubtransmeans.years$ReefType <- ifelse(abusumsubtransmeans.years$ReefType == "Ref (-)", "Control", 
                                      ifelse(abusumsubtransmeans.years$ReefType == "Ref (+)", "Reference", "Other"))
emmAbucorsum.years$ReefType <- ifelse(emmAbucorsum.years$ReefType == "Ref (-)", "Control", 
                                      ifelse(emmAbucorsum.years$ReefType == "Ref (+)", "Reference", "Other"))

### Abundance throughout the years plot
abu.years <- ggplot(data = abusumsubtransmeans.years, aes(x = Study, colour = ReefType, y = Abundance_m2))+
    facet_grid(.~ReefType)+
    geom_jitter(width = 0.2, size = 2)+
    geom_point(data = emmAbucorsum.years, aes(y = response), size = 4, colour='black')+
    geom_errorbar(data = emmAbucorsum.years, width = 0.1, colour='black', size=0.8,
                  aes(y = response, ymin = response - SE, ymax = response + SE))+
    geom_text(data=emmAbucorsum.years, 
              aes(label = .group, y = response + 5*SE), colour = 'black', size = 7)+
    labs(y = expression(paste("Fish abundance ( ", m^-2,")")))+
    scale_y_continuous(trans = 'log10', breaks = c(0.01, 0.1, 1, 10))+
    coord_cartesian(ylim = c(0.001, 11))+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 2.7),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          legend.position="none")
#ggsave("Fish_Abundance_Years.tiff", width = 23, height = 14, units = "cm", dpi=1200, compression = "lzw")

```

### Treatment comparisons - Corrected
```{r abundance treatment corrected}

# ---- MODELLING ----

## ==== Model 2020-2021 ====
### Prep data
abusumsubmeans.cor <- merge(surveys[ ,c(1,9)], abusum, by = "SurveyNo", all.x=T)
abusumsubmeans.cor$Abundance_m2 <- ifelse(grepl("Ref", abusumsubmeans.cor$ReefType), abusumsubmeans.cor$Abundance/abusumsubmeans.cor$Area, abusumsubmeans.cor$Abundance / 36) 
abusumsubmeans.cor <- aggregate(Abundance_m2 ~ Transect + Date + Study + ReefType, abusumsubmeans.cor, mean) # Mean simul surveys
abusumsubtransmeans.cor <- aggregate(Abundance_m2 ~ Transect + Study + ReefType, abusumsubmeans.cor, mean) # Mean per Patch

### Add meta
abusumsubmeans.cor <- merge(abusumsubmeans.cor , metadata, all.x=T)
abusumsubtransmeans.cor  <- merge(abusumsubtransmeans.cor, metadata, all.x=T)

### Modelling
#### Prior analysis showed that depth as co-viarate doesn't improve model
#### Log-transformed because of heterogeneity residuals
abusumsubmeans.cor$Abundance_m2[abusumsubmeans.cor$Abundance_m2 == 0] <- min(abusumsubmeans.cor$Abundance_m2[abusumsubmeans.cor$Abundance_m2>0])/2

## ==== 2021 - not adjusted =====
### Select data
abusumsubmeans.2021.cor <- subset(abusumsubmeans.cor, Study == 2021)
abusumsubtransmeans.2021.cor <- subset(abusumsubtransmeans.cor, Study == 2021)

### Model
lmerAbumeans.2021.cor <- lmer(log10(Abundance_m2) ~ ReefType + (1|Transect), data = abusumsubmeans.2021.cor)
Anova(lmerAbumeans.2021.cor)

### Validation
mod <- lmerAbumeans.2021.cor # set model to be validated
op <- par(mfrow = c(2, 4), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(abusumsubmeans.2021.cor$ReefType, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(fitted(mod) ~ log10(abusumsubmeans.2021.cor$Abundance_m2)) # response data vs fitted
par(op)

### Post hoc
emmAbu.2021.cor <- emmeans(lmerAbumeans.2021.cor, list(pairwise ~ ReefType), adjust='tukey', type = "response")
emmAbusum.2021.cor <- multcomp::cld(emmAbu.2021.cor$emmeans, alpha = 0.05, Letters = letters, reversed = FALSE) # get CLD
emmAbusum.2021.cor <- emmAbusum.2021.cor %>% dplyr::mutate(.group = str_squish(.group)) # remove white spaces


# ---- PLOTS ----

## ==== 2021 - not adjusted ====
### Abundance 2021 - not adjusted
abu.cor <- ggplot(data = abusumsubtransmeans.2021.cor, aes(x = ReefType, colour = ReefType, y = Abundance_m2))+ 
    geom_jitter(width = 0.2, size = 2)+
    geom_point(data= emmAbusum.2021.cor, aes(y = response), colour = 'black', size = 4)+
    geom_errorbar(data = emmAbusum.2021.cor, width = 0.1, colour='black', size=0.8,
                  aes(y = response, ymin = response - SE, ymax = response + SE))+
    geom_text(data=emmAbusum.2021.cor, 
              aes(label = .group, y = response + 3*SE), colour = 'black', size = 7)+
    labs(y = expression(paste("Fish abundance ( ", m^-2,")")), x = "Treatment")+
    scale_y_continuous(trans = 'log10', breaks = c(0.1, 1, 10))+
    coord_cartesian(ylim = c(0.05, 20))+
    scale_color_manual(values=co)+
    theme_bw()+
    theme(axis.title.y = element_text(size = 14, face = "plain", vjust = 2.7),
          axis.text.y = element_text(size = 14, face = "bold", vjust = 0.4),
          axis.title.x = element_blank(),
          axis.text.x = element_blank(),
          legend.position="none")
#ggsave("Fish_Abundance_ARea corrected.tiff", width = 23, height = 14, units = "cm", dpi=1200, compression = "lzw")

# Summary values
abusumsubtransmeans.2021.cor.avg <- data_summary(abusumsubtransmeans.2021.cor, varname = "Abundance_m2", groupnames = c("ReefType"))

```

# Figure compilation
```{r compilation}

# S, Abu and Bio
RAB <- plot_grid(Divplot, Abuplot, Bioplot, nrow = 3, align = "v", rel_heights = c(1,1,1.2),
                 labels = c("A", "B", "C"), label_size = 18)
ggsave("Fish_Richness and Abundance and Biomass for 2021.tiff", width = 18, height = 24, units = "cm", dpi=1200, compression = "lzw", RAB)

# Corrected
COR <- plot_grid(abu.cor, bio.cor, nrow = 2, align = "v", rel_heights = c(1,1.2),
                 labels = c("A", "B"), label_size = 18)
ggsave("Fish_Abundance and Biomass for 2021_Corrected.tiff", width = 18, height = 24, units = "cm", dpi=1200, compression = "lzw", COR)

# Over the years
YEARS <- plot_grid(s.years, abu.years, bio.years, nrow = 3, align = "v", rel_heights = c(1, 1, 1.15),
                 labels = c("A", "B", "C"), label_size = 18)
ggsave("Fish_Richness Abundance and Biomass_Years.tiff", width = 18, height = 24, units = "cm", dpi=1200, compression = "lzw", YEARS)


```

# Export for correlations
```{r export}

COR <- select(divsumsubtransmeans.2021, c("Transect", "ReefType", "S"))
COR$Abundance <- abusumsubtransmeans.2021$Abundance_m2
COR$Biomass <- biosumsubtransmeans.2021$Biomass_ha

write_xlsx(COR, "Structural complexity_Fish surveys_2022-08_Averages per patch.xlsx")

```



